######################################################################################################## 
#                                            Updated.CONF                                              # 
#======================================================================================================# 
#                                            By NADAL1905                                              # 
######################################################################################################## 
 
[global] 
logfile                       = /tmp/ncam.log  
clienttimeout                 = 12000 
fallbacktimeout               = 3000 
bindwait                      = 60 
netprio                       = 1 
nice                          = -2 
maxlogsize                    = 1024 
waitforcards                  = 0 
waitforcards_extra_delay      = 200 
preferlocalcards              = 1 
readerrestartseconds          = 1 
dropdups                      = 1 
lb_nbest_readers              = 4 
lb_mode                       = 0 
lb_save                       = 200 
lb_nfb_readers                = 2 
lb_max_readers                = 4 
ecmfmt                        = P: c:0p:s:d:i #ECM_L:l #CW=w HOP:j 
resolvegethostbyname          = 1 
disablecrccws                 = 1 
disablecrccws_only_for        = 0E00:000000;1819:00006D;098C:000000;09C4:000000;098D:000000;0500:030B00,032830,041950,042800,042820,050F00,051A00;1811:003311,003315;1819:00006D;1884:000000;1709:000000;1708:000000 
cccam_cfg_enabled             = 1 
cccam_cfg_path                = /mnt/media_rw/mmcblk1p1/AutoInstaller/cache 
cccam_cfg_repetitions_forced  = 1 
 	
[cache] 
cwcycle_onbad                 = 0 
cwcycle_allowbadfromffb       = 1 
cwcycle_usecwcfromce          = 1 
 
[newcamd] 
port                          = 12121@0000:000000 
key                           = 0102030405060708091011121314 
mgclient                      = 1 
 
[streamrelay] 
stream_ecm_delay              = 5 
stream_relay_ctab             = 09C4,098C,098D 
stream_relay_enabled          = 1 
stream_emm_enabled            = 5 
stream_relay_buffer_time      = 1 
 
[dvbapi] 
enabled                       = 1 
au                            = 1 
pmt_mode                      = 5 
delayer                       = 60 
user                          = dvbapiau 
read_sdt                      = 1 
write_sdt_prov                = 1 
extended_cw_api               = 1 
demuxer_fix                   = 1 
 
[webif] 
httpport                      = 8080 
#httpcss                       = /mnt/media_rw/mmcblk1p1/iap/plugin/skins/modern_css.css 
httpscript                    = /mnt/media_rw/mmcblk1p1/iap 
#httppiconpath                 = /mnt/media_rw/mmcblk1p1/iap/plugin/picons 
http_prepend_embedded_css     = 1 
httprefresh                   = 30 
httphideidleclients           = 0 
httpshowpicons                = 1 
httppiconsize                 = 40 
httpshowmeminfo               = 1 
httpshowreaderinfo            = 1 
httpallowed                   = 127.0.0.1,0.0.0.0-255.255.255.0,10.0.0.0-10.255.255.255,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,255.255.255.255 
httposcamlabel                = NADAL1905 
  
